services:
  web:
    build:
      context: ..
      dockerfile: docker/web.Dockerfile
    ports:
      - "9901:9901"
    volumes:
      - ..:/app:delegated
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - HOST=0.0.0.0
    command: ["yarn", "dev"]
  ws-backend:
    build:
      context: ..
      dockerfile: docker/ws.Dockerfile
    ports:
      - "9901:9901"
    volumes:
      - ..:/app:delegated
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - HOST=0.0.0.0
    command: ["yarn", "dev"]